# Generated by Django 3.1.7 on 2021-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fifties',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='hundreds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_runs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='played',
            field=models.IntegerField(),
        ),
    ]
